# version isn't needed as of 2020 for docker compose CLI. 
# All 2.x and 3.x features supported
# version: '2'

# based off compose-sample-2, only we build nginx.conf into image
# uses sample HTML static site from https://startbootstrap.com/themes/agency/

services:
  proxy:
    build:
      context: .
    image: custom-drupal 
    ports:
      - '80:80'
  mariadb:
    image: mariadb:10.4
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=mariadb
      - MARIADB_USER=mariadbuser
      - MARIADB_PASSWORD=mariadbpassword
    volumes:
      - drupal-data:/var/lib/mysql

volumes:
  drupal-data:
